### ISSUE TITLE
EI sequences, endpoints pages do not honor <ItemsPerPage> in carbon.xml

### ISSUE THREAD

**Issue by shazni** [wso2/carbon-mediation#929]
**Description:**
Sequences, endpoints pages do not seem to honor <ItemsPerPage> configuration in the carbon.xml. 

**Affected Product Version:**
EI 6.1.1

**Steps to reproduce:**
Add number of sequences (around 20) in the EI and change the <ItemsPerPage> (e.g 3) in the carbon.xml and restart. Navigate to sequences pages. It seems it doesn't show 3 entries per page.

**Comment by nandika** [comment]
Duplicate issue
