### ISSUE TITLE
dispatch.custom.sequence property is not working for inboundEndpoint for WebSocket

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/carbon-mediation#977]
**Description:**
Improvement done in  https://github.com/wso2/carbon-mediation/pull/771 has removed calling custom sequence for web socket invocation. See the section  https://github.com/wso2/carbon-mediation/commit/71ccc706e47974b05d9398bc65b16b3df6207927#diff-e3fbff5c08c529005cf656326b41b622L462 

As a result, we cannot upgrade mediation components in API Manager. current mediation version used in APIM is 4.6.10 and we have enabled <dispatch.custom.sequence> property in our inboundEndpoint file to call the correct endpoint once we do authentication handling from our custom ChannelInboundHandlerAdapter implementation. see https://github.com/wso2/carbon-apimgt/blob/v6.2.93/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/WebsocketInboundHandler.java#L140

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v4.6.20 + 
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nandika** [comment]
Fix is merged
